---
name: simpleflaskapp-deployment
director_uuid: ba9d766d-88ec-4b44-94ce-450f3087e971

releases:
- {name: simpleflaskapp, version: latest}

resource_pools:
- name: default
  network: default
  stemcell:
    name: bosh-openstack-kvm-ubuntu-trusty-go_agent
    version: 3215.4
  cloud_properties:
    instance_type: m1.small

networks:
- name: default
  type: dynamic
  cloud_properties:
    net_id: a2f6db65-99ca-481a-9e97-fc9952f8b791

compilation:
  workers: 1
  network: default
  reuse_compilation_vms: true
  cloud_properties:
    instance_type: m1.small

update:
  canaries: 1
  max_in_flight: 3
  canary_watch_time: 15000-30000
  update_watch_time: 15000-300000

jobs:
- name: simpleflaskapp
  instances: 1
  templates:
  - {name: simpleflaskapp, release: simpleflaskapp}
  resource_pool: default
  networks:
  - name: default

properties:
  simpleflaskapp:
    port: 8080

