---
name: simpleflaskapp-deployment
director_uuid: CHANGE_ME

releases:
- {name: simpleflaskapp, version: latest}

resource_pools:
- name: default
  network: default
  stemcell:
    name: bosh-openstack-kvm-ubuntu-trusty-go_agent
    version: latest
  cloud_properties:
    instance_type: m1.small

networks:
- name: default
  type: dynamic
  cloud_properties:
    net_id: CHANGE_ME

compilation:
  workers: 1
  network: default
  reuse_compilation_vms: true
  cloud_properties:
    instance_type: m1.medium

update:
  canaries: 1
  max_in_flight: 3
  canary_watch_time: 15000-30000
  update_watch_time: 15000-300000

jobs:
- name: simpleflaskapp
  instances: 1
  templates:
  - {name: simpleflaskapp, release: simpleflaskapp}
  resource_pool: default
  networks:
  - name: default

properties:
  simpleflaskapp:
    port: 8080

